# Generated by Django 4.2 on 2024-01-06 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0007_alter_musteri_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 22, 17, 5, 494133), editable=False),
        ),
    ]
