# Generated by Django 4.2 on 2023-12-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun_siparis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunsiparis',
            old_name='siparis_id',
            new_name='siparis',
        ),
        migrations.RenameField(
            model_name='urunsiparis',
            old_name='urun_id',
            new_name='urun',
        ),
    ]
