# Generated by Django 4.2 on 2024-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun_siparis', '0002_rename_siparis_id_urunsiparis_siparis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunsiparis',
            name='siparis_durumu',
            field=models.IntegerField(default=0),
        ),
    ]
