# Generated by Django 4.2 on 2023-12-23 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('fiyat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'urun',
            },
        ),
    ]
