# Generated by Django 4.2 on 2023-12-23 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adres', '0001_initial'),
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aciklama', models.TextField()),
                ('toplam_fiyat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('adres_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adres.adres')),
                ('musteri_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='musteri.musteri')),
            ],
            options={
                'db_table': 'siparis',
            },
        ),
    ]
