# Generated by Django 4.2 on 2023-12-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adres',
            old_name='musteri_id',
            new_name='musteri',
        ),
    ]
